runw:
	./moon/moonc game.moon blanke.moon
	./lovec .

runl:
	moon game.moon blanke.moon
	moonc game.moon blanke.moon
	love .

install_linux:
	sudo add-apt-repository ppa:bartbes/love-stable
	sudo apt-get update
	sudo apt install luarocks love
