runw:
	./moon/bin/moonc main.moon game.moon blanke.moon
	./lovec .

runl:
	moon main.moon game.moon blanke.moon
	moonc main.moon game.moon blanke.moon
	love .

install_linux:
	sudo add-apt-repository ppa:bartbes/love-stable
	sudo apt-get update
	sudo apt install luarocks love
